### PR TITLE
Handling of empty arrays in list_of / list_of_objects rules

### LINKED ISSUE #17: Invalid handling of an empty array in list_of/list_of_objects rules
list_of_objects example: http://livr-multi-playground.webbylab.com/#%7B%22rules%22%3A%22%7B%5Cn%20%20a%3A%20%5B%7B%5Cn%20%20%20%20list_of_objects%3A%20%7B%5Cn%20%20%20%20%20%20x%3A%20%5B'required'%5D%2C%5Cn%20%20%20%20%20%20y%3A%20%5B'required'%5D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5D%5Cn%7D%22%2C%22input%22%3A%22%7B%5Cn%20%20a%3A%20%5B%5D%5Cn%7D%22%7D

### PR DESCRIPTION
**Pull request by amakhrov**
Fixes #17

### CODE REVIEW

**Comment by SDSWanderer** [comment]
Well done, but I think we must leave copy of original [LIVR test suite](https://github.com/koorchik/LIVR/tree/master/test_suite) not modified.
So, there is two ways:
- move this new test cases to separate suite
- extend upstream LIVR test suite by create merge request in LIVR specifications repo

**Comment by amakhrov** [comment]
Oh, I didn't realize it's shared between all implementations.

Yeah I believe it should become of this shared test suit. I'll create a PR there


Sent from my T-Mobile 4G LTE Device

<div>-------- Original message --------</div><div>From: Dan <notifications@github.com> </div><div>Date:02/13/2016  12:34 PM  (GMT-08:00) </div><div>To: WebbyLab/php-validator-livr <php-validator-livr@noreply.github.com> </div><div>Cc: amakhrov <amakhrov@inbox.ru> </div><div>Subject: Re: [php-validator-livr] Handling of empty arrays in list_of /
  list_of_objects rules (#18) </div><div>
</div>Well done, but I think we must leave copy of original LIVR test suite not modified.
So, there is two ways:

move this new test cases to separate suite
extend upstream LIVR test suite by create merge request in LIVR specifications repo

**Comment by amakhrov** [comment]
@SDSWanderer The proposed change has been added to the LIVR test suit now: https://github.com/koorchik/LIVR/pull/28
I copied the exact test cases from that repo into this PR.
Please note that  apart from that the original test suit has some more changes. I didn't include them into this PR, since some tests fail on that. It needs a separate PR to fix those issues.

**Comment by SDSWanderer** [comment]
I know about only one original LIVR test case which was modified in PHP implementation suit, and it's also related to handling empty lists. Please describe what your found in some issue.

Anyway, I think we must merge this changes @antonfin @koorchik

**Comment by amakhrov** [comment]
@SDSWanderer more details about the updated test suit in this issue: https://github.com/WebbyLab/php-validator-livr/issues/19

**Comment by amakhrov** [comment]
@SDSWanderer any update on that?

**Comment by SDSWanderer** [comment]
Thank you, good job.

**Pull request merged**
